# Generated by Django 4.1.4 on 2022-12-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_tag_topics_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
