# Generated by Django 4.1.4 on 2022-12-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_topic_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
